### ISSUE TITLE
Scanning doesn't finish.

### ISSUE THREAD

**Issue by Taylorcho123** [tangxiaofeng7/BurpLog4j2Scan#5]
I installed BurpLog4j2Scan but scanning doesn't finish.
How do I do?

https://imgur.com/DMszCxM

**Comment by j0ebarteam** [comment]
Hello, i have the same issue, the status rest in value "scanning" and i have no result

**Comment by tangxiaofeng7** [comment]
Have a look at Extender->Output->show in UI

**Comment by Taylorcho123** [comment]
Hello, the area doesn't output anything.
I think the tool doesn't start at all but just show 'scanning'.

https://imgur.com/a/YUO0n3g

**Comment by Ethan-Black** [comment]
Hi, i have the same issue. There is an error in Extender -> Errors:
java.lang.UnsupportedOperationException: Action is not supported for this parameter type
	at burp.dc0.a(Unknown Source)
	at burp.dc0.removeParameter(Unknown Source)
	at burp.dc0.updateParameter(Unknown Source)
	at burp.ajk.updateParameter(Unknown Source)
	at burp.BurpExtender.checkVul(BurpExtender.java:97)
	at burp.BurpExtender$2$1.run(BurpExtender.java:211)
	at java.lang.Thread.run(Unknown Source)

**Comment by j0ebarteam** [comment]
Hi, i have no error in output but "Show in UI" is choos
![Capture](https://user-images.githubusercontent.com/78352159/146158476-b8bf8d14-322f-46f7-a644-4a6d23771f3e.PNG)
e.

**Comment by tangxiaofeng7** [comment]
@j0ebarteam @Taylorcho123 @Ethan-Black Could me have a look at your request package？

**Comment by Taylorcho123** [comment]
Okay.

![reqimg](https://i.imgur.com/xVXM6Ed.png)
