### ISSUE TITLE
Errors when I load extension in Burp

### ISSUE THREAD

**Issue by ValidCoder** [tangxiaofeng7/BurpLog4j2Scan#6]
Not working...
OS - kali linux 2021.4
My Burp Suite Community Edition - v2021.10.3
Installed JAVA on my PC:
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.13+8-post-Debian-1, mixed mode, sharing)

javac 11.0.13

When I go to Extender -> Extensions -> Add -> Load gradle-wrapper.jar and then appear errors:

java.lang.ClassNotFoundException: burp.BurpExtender
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:398)
at burp.am4.a(Unknown Source)
at burp.am4.(Unknown Source)
at burp.c04.a(Unknown Source)
at burp.h14.lambda$panelLoaded$0(Unknown Source)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

How can I compile this extension?
There is no file - pom.xml - in your directories of BurpLog4j2Scan-master...

**Comment by tangxiaofeng7** [comment]
https://github.com/tangxiaofeng7/BurpLog4j2Scan/releases/download/v1.1/BurpLog4j2Scan-1.0-SNAPSHOT.jar
